Certificate design 96
Apnasite/certificate-assignments pull request #6
Opened 2024-07-16 08:44 UTC by sanketsj07

2024-07-24 08:46 UTC, laxmikant-gaykhee requested changes
- style.css file add in css folder 
-  images add in img folder
-  add preview.index file
-  add font folder

2024-07-25 07:49 UTC, sanketsj07 commented
changed all request

2024-08-06 07:10 UTC, laxmikant-gaykhee commented on SubmittedAssignments/Sanket_Jadhav/preview.html
> +					<div class="recttop3"></div>
the design class should be out side in content class (add in div class="certificate-background")

2024-08-06 07:11 UTC, laxmikant-gaykhee commented on SubmittedAssignments/Sanket_Jadhav/preview.html
> +
-Add Background Div here

2024-08-06 07:14 UTC, laxmikant-gaykhee commented on SubmittedAssignments/Sanket_Jadhav/preview.html
> +					<div class="radius"></div>
-there div also add in background class

2024-09-18 04:15 UTC, KalpeshApnasite requested changes
remove certificate-content from index.html

2024-09-18 17:39 UTC, KalpeshApnasite requested changes
rename the folder name

2024-09-18 17:48 UTC, KalpeshApnasite requested changes

2024-09-18 17:48 UTC, KalpeshApnasite commented on SubmittedAssignments/Sanket_Jadhav/css/style.css
follow the folder name format

2024-09-21 04:09 UTC, merged