Bhosle Mahesh 69,83
Apnasite/certificate-assignments pull request #70
Opened 2024-09-16 09:34 UTC by Bhosle07

2024-09-18 04:14 UTC, KalpeshApnasite requested changes
don't use px

2024-09-18 04:14 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_83/css/style.css
> +    height: 2px;
don't use px

2024-09-18 17:44 UTC, KalpeshApnasite requested changes

2024-09-18 17:44 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_83/css/style.css
> +    letter-spacing: 1px;
do not use px

2024-09-18 17:44 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_69/index.html
> +<body>
add only certificate-background in index.html

2024-09-18 17:44 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_83/.vscode/settings.json
remove this file

2024-09-18 17:44 UTC, KalpeshApnasite commented on SubmittedAssignments/Bhosle_Mahesh_crt_76.jpg/css/style.css
follow folder name format

2024-09-20 11:58 UTC, Adarshovhal reviewed
In css file mm and pt unit are used. Not px & em used anywhere.
All classes in the previous.html file.
Background classes in the index.html file.
Code was good in structure.

2024-09-20 12:45 UTC, merged