Adarsh-Ovhal-59
Apnasite/certificate-assignments pull request #71
Opened 2024-09-16 10:51 UTC by Adarshovhal

2024-09-18 04:12 UTC, KalpeshApnasite requested changes
change folder name Adarsh_Ovhal_59

2024-09-18 17:47 UTC, KalpeshApnasite requested changes

2024-09-18 17:47 UTC, KalpeshApnasite commented on SubmittedAssignments/Adarsh_Ovhal_59/css/style.css
> +    width: 250px;
do not use px

2024-09-18 17:47 UTC, KalpeshApnasite commented on SubmittedAssignments/Adarsh_Ovhal_59/css/style.css
> +		width: 400px;
do not use px

2024-09-20 11:11 UTC, Bhosle07 reviewed
"Check the folder structure to ensure it follows the correct format. In preview.html, verify all classes are present. In style.css, ensure units of measurement are in mm and pt. In index.html, confirm all background classes are included."

2024-09-20 11:30 UTC, Bhosle07 reviewed
"Check the folder structure to ensure it follows the correct format. In preview.html, verify all classes are present. In style.css, ensure units of measurement are in mm and pt. In index.html, confirm all background classes are included."

2024-09-20 12:47 UTC, merged