Certificate No-91
Apnasite/certificate-assignments pull request #8
Opened 2024-07-17 08:05 UTC by raveeshrajput

2024-07-25 03:54 UTC, laxmikant-gaykhee requested changes
- style.css file add in css folder

2024-09-18 18:02 UTC, KalpeshApnasite requested changes
follow  folder name format

2024-09-19 05:56 UTC, KalpeshApnasite requested changes

2024-09-19 05:56 UTC, KalpeshApnasite commented on SubmittedAssignments/Raveesh_Rajput-108/css/style.css
> +    border-width: 14pt 18pt 0pt 0px;
do not use px

2024-09-21 04:31 UTC, merged